# .github/workflows/backend-workflow.yml
name: Backend Build and Deploy

on:
  push:
    paths:
      - 'backend/**'
    branches: [ main, develop, release, hotfix ]
  pull_request:
    paths:
      - 'backend/**'
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and cache Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./backend
        push: false
        load: true
        tags: backend:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Test Docker image
      run: |
        docker run --rm backend:${{ github.sha }} python -m pytest
