# .github/workflows/frontend-workflow.yml
name: Frontend Build and Deploy

on:
  push:
    paths:
      - 'frontend/**'
    branches: [ main, develop, release, hotfix ]
  pull_request:
    paths:
      - 'frontend/**'
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and cache Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./frontend
        push: false
        load: true
        tags: frontend:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Test Docker container
      run: |
        docker run --rm frontend:${{ github.sha }} npm run test
